@startuml

hide empty members

' Implicit Interfaces
interface Broker {
    Notify(store.Record)
    Subscribe(subId, streamId, Handler)
}

interface Store {
    ReadRecords()
    Begin() store.Tx
    Store()
}

interface Registry {
	LookupType()
	Unmarshal()
	Marshal()
}

interface Tx {
    Commit()
    Rollback()
}

interface Handler {
    Handle(Message)
}

class Po {
    Stream(streamId) *Stream
    Project(streamId, projection)
    Subscribe(subId, streamId, Handler)
}
note left
    Main Entry point
    for the Application
end note

class Stream {
    Project(projection)
    Append(msg)
}

class Message {
    ID
    Stream
    Type
    Data
}


' Connections
Store     -r-> Tx               : Creates

Po      -d->    Stream          : Opens
Po      -d->    Broker          : Subscribes
Stream  -r->    Broker          : Notifies
Stream  -d->    Store           : Reads records
Stream  -d->    Handler         : Projects onto
Stream  -d->    Registry        : Marshals

Broker  -d-> Handler              : Notifies
Handler -> Message              : Reads

@enduml
