on: push
name: Continuous Integration
jobs:
  checks:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: unit
        uses: cedrickring/golang-action@1.5.0
        with:
          args: make test-short
