on: push
name: Continuous Integration
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: test
        uses: cedrickring/golang-action@1.5.0
        with:
          args: make test-short
